## your personal information from LNMarkets (Rufus10 - Mainnet)
lnm_credentials: 
  key: '/yc7NKqrDJLC87PyY8gjyP7NQOKMC0K0U6VdQa5iUqs='
  secret: 'EnKRjabxoq+DNPQnOg90rTCngO8wpW1/R9DPJFQZhvT4QNj7u3CbWPIFrSy5W7kL/UatLsV/h+WbfOYh6Zxp9w=='
  passphrase: '2i274426gjc8j'
  network: 'mainnet'


## your personal information from LNMarkets (Rufus15 - Testnet)
# lnm_credentials: 
#   key: 'dR2dnom1oMljsN33DJjxNA7bSvItEg82sdZ00HjxY7s='
#   secret: '4VW5Zp5K4DqOZC8Zr4jd2dw5Bi/G8nxs9qEK3fQ7aIVGrzjsczMpbZQonKoe89N+V3MwFdUHoYn1ydh7eHf5Rg=='
#   passphrase: 'dg05hcihaci8f'
#   network: 'testnet'



## choose your strategy while affecting True (and False to other strategies)
strategies:
  #Trading strat based on TA Summary: https://www.tradingview.com/symbols/XBTUSD/technicals/
  ta_summary: True
  

## parameters for strategies
ta_summary:
  quantity: 10 #type=int, min=1, quantity of each open position
  leverage: 10 #type=int, min=1, max=100
  takeprofit: 0.02 #type=float, price to reach above (for long) or below (for short) entry price to take profit, 0.2 means take profit 20% above or below entry price 
  stoploss: 0.02 #type=float, price to reach below (for long) or above (for short) entry price to stop loss, 0.1 means stop loss 10% below or above entry price
  interval: '1m' #type=string, available interval between 2 TA summary signals: "1m" for 1 minute, "5m" for 5 minutes, "15m" for 15 minutes, "30m" for 30 minutes, "1h" for 1 hour, "2h" for 2 hours, "4h" for 4 hours, "1d" for 1 day, "1W" for 1 week, "1M" for 1 month
  timeout: 60 #type=int, min=1, number of minutes the trading strat will be running2